### ISSUE TITLE
Algorithm doesn't seem to work for the following example "Reactive JS library for a really long"

### ISSUE THREAD

**Issue by CallumHemsley** [shuding/react-wrap-balancer#25] opened 2023-01-09 20:23 UTC
Hello!

Really awesome library 👏 I noticed for this specific example, I don't get a balanced text, with a hanging word:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12123687/211400602-69c96208-77da-41ef-a387-3b28aeebf10d.png">

Here is a code sandbox with the example, it should be noted that the maxWidth has been set to 400 (as I was playing around with the idea of making this for RN): https://codesandbox.io/p/sandbox/reverent-lake-mkf42q

What I would expect is something like (achieved by setting the max width of the parent div to 200):
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12123687/211400975-fa89637b-c525-4cb7-b396-4bec97c958aa.png">

Let me know if I'm missing something!

**Comment by shuding** [comment] 2023-01-10 14:30
Oh interesting case, I think the problem is about rounding! The current width (288.33px) is already the minimal but we rounded it to 288px and did the binary search in [288px/2, 288px] which causes the line break.

**Comment by shuding** [comment] 2023-01-10 14:40
The tricky thing is `clientWidth` only gives rounded values, but `getBoundingClientRect` is too expensive to use. I think we can safely add 0.5 to the upper bound since we are using `max-width`, it will be pretty safe.

**Comment by CallumHemsley** [comment] 2023-01-10 15:45
Wow what a rapid response ⚡ Happy to help test 👍 Will test later today too

**Comment by shuding** [comment] 2023-01-22 14:29
Fixed in #34, I tested locally :)

**Closed** 2023-01-22 14:29 UTC
Labels: bug

**Comment by CallumHemsley** [comment] 2023-01-23 09:27
Thanks @shuding !!
