### ISSUE TITLE
CLS / Flicker

### ISSUE THREAD

**Issue by mdugue** [shuding/react-wrap-balancer#18] opened 2023-01-05 09:06 UTC
Hey, @shuding great library and great idea to target this nitty gritty details in such a nice way 🥳!

Looking carefully at the page load I did realize a little flickering on initial page load. The video below demonstrates it at a slow-motion speed of 10%. 

I assume, this comes from transitioning SSR -> client side rendering, where SSR can't apply reasonable balancing. Still, doesn't this break with the claim of not causing layout shifts? Are there a workarounds / ideas on improving that behavior?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/894149/210741714-94aea516-13d3-4f1b-93ee-c7f12ae9a7cf.gif)

**Comment by shuding** [comment] 2023-01-05 11:13
Thanks, we got some bug reports from Twitter about this too. The layout shift here is caused by a bug related to custom fonts, not because of SSR.

I'm thinking about a fix for this, but the downside is we might have to change the API a bit by adding a `<Provider>`.

**Closed** 2023-01-05 13:22 UTC
Labels: bug

**Comment by mdugue** [comment] 2023-01-05 13:54
wow, @shuding that was a quick answer and fix 💪👌. Thanks a lot
